### ISSUE TITLE
SOR4Explorer dont start

### ISSUE THREAD

**Issue by Kagero911** [jlcebrian/SOR4Explorer#4]
its work ok but today i tried to start SOR4Explorer and for now this program not launched at all. Just nothing. Maybe i add to many mods (sprites), and when i test mods i will add to much idk. Any solution to fix it? Also i tried  delete %LOCALAPPDATA%\SOR4 Explorer folder and files inside. It just stop working...

**Comment by 1wi11wq** [comment]
You are fixed?

**Comment by francescobau** [comment]
> 
> 
> its work ok but today i tried to start SOR4Explorer and for now this program not launched at all. Just nothing. Maybe i add to many mods (sprites), and when i test mods i will add to much idk. Any solution to fix it? Also i tried delete %LOCALAPPDATA%\SOR4 Explorer folder and files inside. It just stop working...

Same issue here.
After I moved the SSD into another PC, SOR4 Explorer just won't work.
And I tried to delete the files in AppData/Local, but it was a huge mistake, because I realized that I needed these files to do a proper Restore, and I guess we were supposed to use **dotnet** command properly in order to perform a restore.
Now I'm stuck.
I tried to extract the source code, and do
**cd [Path_To_Folder]**
and then
**dotnet run**
It finally opens the window, in which you are supposed to drag the SOR4 Folder into there, but, unfortunately... IT DOESN'T LET ME DO IT!!!!
I tried to use the commands
**dotnet clean**
**dotnet restore**
...but I had no luck, unfortunately...

I hope @jlcebrian will give us a guide to fix this issue...

**Comment by anhell-dotcom** [comment]
Me too, one day it just stopped working

**Comment by kfcrispy** [comment]
I last successfully used SOR4Explorer in January of this year. I feel that Windows Defender is automatically and silently blocking it from running, but I've tried all kinds of exceptions and still can't get it to run. If anyone ever had it stop running completely and figured out how to fix it, please let me know!

**Comment by jlcebrian** [comment]
I have no idea about this issue because the app works fine in my computers, both the EXE in the release and the source after following the instructions. You could try to download the .Net SDK and the source and run it manually.

**Comment by francescobau** [comment]
Hello there @jlcebrian !!!!

I've already tried to do that, but without luck.

In that case, it launches, but, when it says to "Drag the folder" or something like that, it won't let me do that anymore. It refuses anything, I can't drag anything!

I "solved" this issue by using another PC, and then copy the entire SOR4 Folder in the other PC, but I can use the SOR4Explorer from the other PC only.

It's like you can "drag" only once and forever... But I don't know how am I supposed to do a "reset", and re-install.

**Comment by jlcebrian** [comment]
Interesting. That looks like an entirely different issue, my guess is that the game has received updates which has changed something in its data files in a way SOR4Explorer no longer can recognize it.

**Comment by francescobau** [comment]
Unfortunately, I don't think that's the case...
I've made this test with a cracked version of the game. So it won't update.

It works only the first time, but, if you mess up, or something bad happens, then, even if you restore completely the SOR4 folder, and delete old SOR4Explorer data, in order to restart over, it will give the same issues.

Maybe we are missing some folders we can't see...

Could you tell us the paths of SOR4Explorer we must delete before attempting to starting over one more time, please?

That would be much appreciated!

**Comment by jlcebrian** [comment]
SOR4Explorer saves its local data to a folder called "SOR4 Explorer" inside the folder addressed by the environment variable %LOCALAPPDATA%, which should be C:\Users\<your username>\AppData\Local 

It should write a file called 'settings.json' to that folder, in addition to some backups of the original game files. Deleting this folder *should* produce the same effect as running the program for the first time, since (as far as I remember) no other state is saved anywhere else.

**Comment by francescobau** [comment]
Unfortunately I already tried that, but without luck...

I still have the same issues (SOR4 Explorer doesn't open, the `dotnet run` command on the Source Code works, but I can't drag my SOR4 Folder in the Window, like I used to do the first time)

It seems it's not just about that folder in Local... There must be a side effect somewhere else.

**Comment by shingler** [comment]
I followed 

> SOR4Explorer saves its local data to a folder called "SOR4 Explorer" inside the folder addressed by the environment variable %LOCALAPPDATA%, which should be C:\Users<your username>\AppData\Local
> 
> It should write a file called 'settings.json' to that folder, in addition to some backups of the original game files. Deleting this folder _should_ produce the same effect as running the program for the first time, since (as far as I remember) no other state is saved anywhere else.

I followed with this ,but without luck. But I find some interesting that I renamed the SOR4Explorer.exe to SOR4Explorer1.exe, and then you know what? It works!

**Comment by francescobau** [comment]
Interesting.
I recently archived my games somewhere else, so I can't test this thing anymore.

Anyway, out of curiosity, I tried to search the key "SOR4Explorer" in the Registry Editor (regedit), and... I found something.

In
Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\MuiCache
![immagine](https://user-images.githubusercontent.com/56580849/137333100-4504ee9b-4b55-481d-9222-e4e95598e6df.png)

My suspect is that we should remove the keys in the registry, because they might be corrupted, and we can do a clean reinstall of the SOR4Explorer.exe .

Also, there might be more keys in the Registry elsewhere, so make sure you find all occurrences of "SOR4Explorer" before you attempt to do a clean reinstall.
Also, a reboot is recommended.

I can't guarantee this works, but your last comment makes me suspect about this issue even more...

P.S. Make sure to do a backup of your registry if you want to proceed, because it is very fragile!
